In [1]:
import numpy as np

In [2]:
x = np.array([7,5,6,3,2,6,9,5])

In [3]:
x

array([7, 5, 6, 3, 2, 6, 9, 5])

In [4]:
x = np.array([[7,5,3],[3,6,9],[1,5,9]])
x

array([[7, 5, 3],
       [3, 6, 9],
       [1, 5, 9]])

In [5]:
x.shape

(3, 3)

In [6]:
x.size

9

In [7]:
x.argmax()

5

In [9]:
x.argmax(axis=1)

array([0, 2, 2], dtype=int64)

In [11]:
np.square(45)

2025

In [12]:
np.sin(np.deg2rad(90))

1.0

In [13]:
m = np.matrix([[3,2,6],[1,4,9],[6,2,5]])
m

matrix([[3, 2, 6],
        [1, 4, 9],
        [6, 2, 5]])

In [14]:
np.linalg.inv(m)

matrix([[-0.07142857, -0.07142857,  0.21428571],
        [-1.75      ,  0.75      ,  0.75      ],
        [ 0.78571429, -0.21428571, -0.35714286]])

In [16]:
np.linalg.det(m)

-28.00000000000001

In [17]:
np.linalg.eig(m)

(array([12.5396547 , -1.78828813,  1.24863343]),
 matrix([[ 0.49523523,  0.34754151,  0.14525819],
         [ 0.65702095,  0.77059892, -0.95056535],
         [ 0.56838854, -0.53422112,  0.27445506]]))